### ISSUE TITLE
Highlight differences?

### ISSUE THREAD

**Issue by csandell** [lfalck/Compare-RemoteAssemblies#1]
Nice work, i will use this one at many of my customers.

Is it maybe possible to add functionality to highlight differences?
Maybe some color when the file versions differences between the environments.....

**Comment by lfalck** [comment]
Thanks!

I don't think that's possible unfortunately, there does not seem to be a way to change the text or background color  with [Out-GridView](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-gridview?view=powershell-5.1) which is used to display the interface.

However, i could add a new column "Assembly differs between servers" (Yes/No), then you could filter and sort on that. What do you think?

**Comment by lfalck** [comment]
Closing this one due to inactivity.
